  SLACK_FAILURE:         '#ff0000'
  SLACK_SUCCESS:         '#00ff00'
  SLACK_ICON:            https://raw.githubusercontent.com/DFE-Digital/get-into-teaching-api/master/.github/image.png?size=48
  SLACK_USERNAME:        GiT Workflows
  SLACK_FOOTER:          GiT Cypress Tests 
  DOCKERHUB_REPOSITORY:  DFE-Digital/get-into-teaching-frontend-tests/dfecypress
  DOMAIN:                london.cloudapps.digital
  APPLICATION:           GiT Cypress Tests

