module.exports = class Navlinks {
	static fundingYourTraining = "/funding-your-training";
	static getAnAdviser = "/tta-service";
	static stepsToBecomeATeacher = "/steps-to-become-a-teacher";
	static waysToTrain = "/ways-to-train";
	static returningToTeaching = "/returning-to-teaching";
	static lifeAsATeacher = "/a-day-in-the-life-of-a-teacher";
	static salariesAndBenefits = "/salaries-and-benefits";
	static myStoryIntoTeaching = "/my-story-into-teaching";
	static careerChangers = "/my-story-into-teaching/career-changers";
	static internationalCareerChangers = "/my-story-into-teaching/international-career-changers";
	static teacherTrainingStories = "/my-story-into-teaching/teacher-training-stories";
	static makingADifference = "/my-story-into-teaching/making-a-difference";
	static careerProgression = "/my-story-into-teaching/career-progression";
	static returners = "/my-story-into-teaching/returners";
	static events = "/events";
	static mailingListSignup = "/mailinglist/signup/name";
	static covid19 = "/covid-19";
	static facebook = "https://www.facebook.com/getintoteaching";
	static instagram = "https://www.instagram.com/get_into_teaching/";
	static linkedin =
		"https://www.linkedin.com/company/9258520?trk=tyah&trkInfo=idx%3A1-1-1%2CtarId%3A1424345327269%2Ctas%3Aget+into+teaching";
	static twitter = "https://twitter.com/getintoteaching";
	static youtube = "http://www.youtube.com/user/getintoteaching";
	static mailingListSignupUrl = "https://get-into-teaching-app-test.london.cloudapps.digital/mailinglist/signup/name";
	static teachInScotland = "https://teachinscotland.scot";
	static teachInWales = "https://www.discoverteaching.wales/routes-into-teaching/";
	static teachInNorthernIreland =
		"https://www.education-ni.gov.uk/articles/initial-teacher-education-courses-northern-ireland";
	static teachingRoleInEngland = "https://teaching-vacancies.service.gov.uk/";
	static feedback = "https://docs.google.com/forms/d/e/1FAIpQLSdBXbU5nwP6_3TH7HY5rB4ehkSDNzfKqB5X2G7wG4K6LY97-g/viewform";
	static internationalStudent = "/train-to-teach-in-england-as-an-international-student";
	static exploreOnlineQAs = "/event-categories/online-q-as";
	static exploreSchoolAndUniversity = "/event-categories/school-and-university-events";
	static assessmentOnlyProviders = "/assessment-only-providers";
	static becomeATeacherInEngland = "/guidance/become-a-teacher-in-england";
	static trainToTeachEvents = "/event-categories/train-to-teach-events";
	static improveYourSubjectKnowledge = "/improve-your-subject-knowledge";
};
