---
name: Cypress
on:
  workflow_dispatch:
    inputs:
      application:
        description: 'BOTH APP or TTA'
        required: true
        default:  'BOTH'

  schedule:
    - cron: "0 23 * * *"
jobs:
  cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:   Run the Tests for Adviser
        if:  github.event.inputs.application == 'TTA' || github.event_name == 'schedule' || github.event.inputs.application == 'BOTH' 
        run: |
          docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test  dfedigital/dfecypress:latest \
                             --spec cypress/integration/teacher-training-adviser.spec.js  --headless --browser chrome 
          cat ./cypress/end-2-end-test-report.json | jq  -r ".results[].suites[].tests[] | {title , pass} | select(.pass=="false" ) | .title" > ${PWD}/run1
        env:
              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
        
      - name:   Run the Tests for Application Mailing List
        if:  github.event.inputs.application == 'APP' || github.event_name == 'schedule' || github.event.inputs.application == 'BOTH'
        run: |
             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test dfedigital/dfecypress:latest \
                             --spec cypress/integration/mailinglist-signup-flow.spec.js --headless --browser chrome 
             cat ./cypress/end-2-end-test-report.json | jq  -r ".results[].suites[].tests[] | {title , pass} | select(.pass=="false" ) | .title" > ${PWD}/run2
        env:
              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
        
      - name:   Run the Tests for Application Event Sign Up
        if:  github.event.inputs.application == 'APP' || github.event_name == 'schedule' || github.event.inputs.application == 'BOTH' 
        run: |
             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test dfedigital/dfecypress:latest \
                             --spec cypress/integration/event-signup-flow.spec.js --headless --browser chrome 
             cat ./cypress/end-2-end-test-report.json | jq  -r ".results[].suites[].tests[] | {title , pass} | select(.pass=="false" ) | .title" > ${PWD}/run3
        env:
              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
        
      - name:   Run the Tests for Application Home Page
        if:  github.event.inputs.application == 'APP' || github.event_name == 'schedule' || github.event.inputs.application == 'BOTH'
        run: |
             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test dfedigital/dfecypress:latest \
                             --spec cypress/integration/homepage-smoke.spec.js --headless --browser chrome 
             cat ./cypress/end-2-end-test-report.json | jq  -r ".results[].suites[].tests[] | {title , pass} | select(.pass=="false" ) | .title" > ${PWD}/run3
        env:
              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Videos
          path: ./cypress/videos/
          if-no-files-found: ignore 
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Screenshots
          path: ./cypress/screenshots/
          if-no-files-found: ignore

      - name: Count Failures
        id:  failures
        if: always()
        run: |
            errors=$( cat ${PWD}/run1 ${PWD}/run1 ${PWD}/run2 ${PWD}/run3 ${PWD}/run4 2>/dev/null )
            if [[ $(echo "${errors}" | wc -l) -gt 0  ]]
            then
                 echo ::set-output name=numnber::$(echo "${errors}" | wc -l)
                 echo ::set-output name=errors::"${errors}"
                 exit 1
            fi
            exit 0

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_CHANNEL: getintoteaching_tech
           SLACK_COLOR: '#3278BD'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_MESSAGE: |
                           ${{steps.failures.outputs.number}} Cypress tests have failed

                           ${{steps.failures.outputs.errors}}
           SLACK_TITLE: 'Failure: Cypress tests'
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
