---
name: Cypress
on:
  workflow_dispatch:
    inputs:
      application:
        description: 'BOTH APP or TTA'
        required: true
        default:  'BOTH'

  schedule:
    - cron: "0 23 * * *"
jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.select-tests.outputs.test }}
    steps:
      - name: Select Tests
        id: select-tests
        run: |
             if  [[ ${{github.event_name}} == 'schedule'  ]]
             then
                   tests='{"tests":[ teacher-training-adviser, mailinglist-signup-flow, homepage-smoke, event-signup-flow ]}' 
             elif  [[ ${{github.event.inputs.application}} == 'APP' ]] 
             then
                   tests='{"tests":[ mailinglist-signup-flow, homepage-smoke, event-signup-flow ]}' 
             elif  [[ ${{github.event.inputs.application}} == 'TTA'  ]]
             then
                   tests='{"tests":[ teacher-training-adviser ]}' 
             elif  [[ ${{github.event.inputs.application}} == 'BOTH' ]]
             then
                   tests='{"tests":[ teacher-training-adviser, mailinglist-signup-flow, homepage-smoke, event-signup-flow ]}' 
             else
                   exit 1
             fi

             echo "::set-output name=tests::$tests"

  cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      fail-fast: false # doesn't stop other specs runs even if one fails
      matrix:
        spec: ${{ fromJson(needs.set-matrix.outputs.tests) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ensure latest version of image
        run:  docker pull dfedigital/dfecypress:latest
        
      - name: Run ${{ matrix.spec}} Spec
        run: |
          docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test  dfedigital/dfecypress:latest \
                             --spec cypress/integration/${{ matrix.spec}}.spec.js --headless --browser chrome 
        env:
              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
        
      - name: Upload reports artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Reports
          path: ./cypress/reports/
          if-no-files-found: ignore

      - name: Upload video artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Videos
          path: ./cypress/videos/
          if-no-files-found: ignore 
          
      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Screenshots
          path: ./cypress/screenshots/
          if-no-files-found: ignore

      - name: Count Failures
        id:  failures
        if: always()
        run: |
            cat ./cypress/reports/*.json | jq  -r ".results[].suites[].tests[] | {title , pass} | select(.pass=="false" ) | .title" > /tmp/$$.tmp
            if [[ $(cat /tmp/$$.tmp | wc -l) -gt 0  ]]
            then
                 i=0
                 echo ::set-output name=adverb::""
                 while IFS= read -r line
                 do
                   if [[ $i -gt 10 ]]
                   then
                      echo ::set-output name=adverb::first
                      break
                   fi
                   i=$((i+1))
                   echo ::set-output name=message${i}::"  - ${line}"
                 done <  /tmp/$$.tmp
                 echo ::set-output name=display::${i}
                 echo ::set-output name=number::$(cat /tmp/$$.tmp | wc -l)
                 exit 1
            fi
            exit 0

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           SLACK_CHANNEL: getintoteaching_tech
           SLACK_COLOR: '#3278BD'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_TITLE: 'STEVE TEST - Failure running Cypress test ${{ matrix.spec}}'
           SLACK_MESSAGE: |
                           ${{steps.failures.outputs.number}} Cypress tests have failed,
                           here are the ${{steps.failures.outputs.adverb}} ${{steps.failures.outputs.display}} failures
                           ${{steps.failures.outputs.message1}}
                           ${{steps.failures.outputs.message2}}
                           ${{steps.failures.outputs.message3}}
                           ${{steps.failures.outputs.message4}}
                           ${{steps.failures.outputs.message5}}
                           ${{steps.failures.outputs.message6}}
                           ${{steps.failures.outputs.message7}}
                           ${{steps.failures.outputs.message8}}
                           ${{steps.failures.outputs.message9}}
                           ${{steps.failures.outputs.message10}}

