---
name: Cypress
on:
  workflow_dispatch:
    inputs:
      application:
        description: 'BOTH APP or TTA'
        required: true
        default:  'BOTH'

  schedule:
    - cron: "0 23 * * *"
jobs:
  cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Count Failures
        id:  failures
        if: always()
        run: |
            cat ./cypress/reports/*.json | jq  -r ".results[].suites[].tests[] | {title , pass} | select(.pass=="false" ) | .title" > /tmp/$$.tmp
            if [[ $(cat /tmp/$$.tmp | wc -l) -gt 0  ]]
            then
                 echo ::set-output name=number::$(cat /tmp/$$.tmp | wc -l)
                 echo ::set-output name=errors::"$( cat /tmp/$$.tmp)"
                 echo "$( cat /tmp/$$.tmp)"
                 exit 1
            fi
            exit 0

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_CHANNEL: getintoteaching_tech
           SLACK_COLOR: '#3278BD'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_TITLE: 'Failure running Cypress tests'
           SLACK_MESSAGE: |
                           ${{steps.failures.outputs.number}} Cypress tests have failed
                           ${{steps.failures.outputs.errors}}
           SLACK_WEBHOOK: ${{ secrets.TEST_SLACK_WEBHOOK }}
           SLACK_FOOTER:  Steves Test
