---
name: Cypress Testing (dev) (passive)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
jobs:
  cypress:
    name: Run Cypress Tests (dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: passive_tests 

      - name:   Run the Tests
        run: |
             docker build . -t cypress-image
             docker run -i -v $PWD:/test -w /test cypressi-image
        
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: Videos
          path: ./cypress/videos/

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: Screenshots
          path: ./cypress/screenshots/
