---
name: Cypress Testing against Test Environment
on:
  workflow_dispatch:
    inputs:
      application:
        description: 'BOTH APP or TTA'
        required: true
        default:  'BOTH'

  schedule:
    - cron: "0 23 * * *"
jobs:
  cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:   Run the Tests for BOTH
        if:  github.event_name == 'schedule' or  github.event.inputs.application == 'BOTH' 
        run: |
             docker build . -t cypress-image --pull
             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test cypress-image --headless --browser chrome 
        env:
              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
        
      - name:   Run the Tests for TTA
        if:  github.event.inputs.application == 'TTA'
        run: |
             docker build . -t cypress-image --pull
             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test cypress-image --spec cypress/integration/teacher-training-adviser.spec.js  --headless --browser chrome 
        env:
              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
        
      - name:   Run the Tests for APP
        if:  github.event.inputs.application == 'APP'
        run: |
             docker build . -t cypress-image --pull
             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test cypress-image --spec cypress/integration/mailinglist-signup-flow.spec.js --headless --browser chrome 
             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test cypress-image --spec cypress/integration/event-signup-flow.spec.js --headless --browser chrome 
             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test cypress-image --spec cypress/integration/homepage-smoke.spec.js --headless --browser chrome 
        env:
              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Videos
          path: ./cypress/videos/
          if-no-files-found: ignore 
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Screenshots
          path: ./cypress/screenshots/
          if-no-files-found: ignore

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_CHANNEL: getintoteaching_tech
           SLACK_COLOR: '#3278BD'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_MESSAGE: ':disappointed_relieved: Pipeline Failure :disappointed_relieved:'
           SLACK_TITLE: 'Failure: ${{ github.workflow }}'
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
