---
name: Cypress
on:
  push:
    branches:
      - sfawcett123-patch-1
jobs:
  cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Count Failures
        id:  failures
        if: always()
        run: |
            cat ./cypress/reports/*.json | jq  -r ".results[].suites[].tests[] | {title , pass} | select(.pass=="false" ) | .title" > /tmp/$$.tmp
            echo "SLACK_ERROR_MESSAGE=$(< /tmp/$$.tmp)" >> $GITHUB_ENV
            exit 0

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_CHANNEL: getintoteaching_tech
           SLACK_COLOR: '#3278BD'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_TITLE: 'Failure running Cypress tests'
           SLACK_MESSAGE: ${{ env.SLACK_ERROR_MESSAGE }}
           SLACK_WEBHOOK: ${{ secrets.TESTING_SLACK_WEBHOOK }}
           SLACK_FOOTER:  Steves Test
