---
name: Cypress Testing against Test Environment
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
jobs:
  cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:   Run the Tests
        run: |
             docker build . -t cypress-image --pull
             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test cypress-image 
        env:
              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Videos
          path: ./cypress/videos/
          if-no-files-found: ignore 
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Screenshots
          path: ./cypress/screenshots/
          if-no-files-found: ignore

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_CHANNEL: getintoteaching_tech
           SLACK_COLOR: '#3278BD'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_MESSAGE: ':disappointed_relieved: Pipeline Failure :disappointed_relieved:'
           SLACK_TITLE: 'Failure: ${{ github.workflow }}'
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
