---
name: Cypress
on:
 workflow_call:
    inputs:
      application:
        required: true
        type: string
      reference:
        required: true
        type: string  
    secrets:
      AZURE_CREDENTIALS:
        required: true
      KEY_VAULT:
        required: true

 workflow_dispatch:
    inputs:
      application:
        description: 'BOTH, APP or TTA'
        required: true
        default:  'BOTH'
      reference:
        description: 'Entered by automation only'
        required: true
        default:  'Cypress'   

 schedule:
    - cron: "0 23 * * *"
jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.select-tests.outputs.tests }}
    steps:
            
      - name: Select Tests
        id: select-tests
        run: |
             if  [[ "${{github.event_name}}" == "schedule"  ]]
             then
                   tests='{"tests":[ "get_an_adviser", "mailing_list" ]}' 
             elif  [[ "${{github.event.inputs.application}}" == "APP" || "${{inputs.application}}" == "APP" ]] 
             then
                   tests='{"tests":[ "mailing_list" ]}' 
             elif  [[ "${{github.event.inputs.application}}" == "TTA" || "${{inputs.application}}" == "TTA"  ]]
             then
                   tests='{"tests":[ "get_an_adviser"]}' 
             elif  [[ "${{github.event.inputs.application}}" == "BOTH" || "${{inputs.application}}" == "BOTH" ]]
             then
                   tests='{"tests":[ "get_an_adviser", "mailing_list" ]}' 
             else
                   exit 1
             fi
             echo ${tests}
             echo "::set-output name=tests::${tests}"

  RunTests:
    name: ${{matrix.tests}}
    env:
      SLACK_FAILURE:         '#ff0000'
      SLACK_SUCCESS:         '#00ff00'
      SLACK_ICON:            https://raw.githubusercontent.com/DFE-Digital/get-into-teaching-api/master/.github/image.png?size=48
      SLACK_USERNAME:        GiT Workflows
      SLACK_FOOTER:          GiT Cypress Tests 
      DOCKERHUB_REPOSITORY:  ghcr.io/dfe-digital/dfecypress
      DOMAIN:                london.cloudapps.digital
      APPLICATION:           GiT Cypress Tests
    runs-on: ubuntu-latest
    environment: Test
    needs: set-matrix
    strategy:
      fail-fast: false # doesn't stop other test runs even if one fails
      matrix: ${{ fromJson(needs.set-matrix.outputs.tests) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - uses: Azure/login@v1.4.2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: DfE-Digital/keyvault-yaml-secret@v1
        id:  keyvault-yaml-secret
        with:
          keyvault: ${{ secrets.KEY_VAULT}}
          secret: INFRA-KEYS
          key: SLACK-WEBHOOK, HTTP-USERNAME, HTTP-PASSWORD, EVENT-USER-EMAIL-API-KEY, MAILING-LIST-USER-EMAIL-API-KEY, TTA-USER-EMAIL-API-KEY, PERCY-TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Set Configuration
        id:   config
        run: |
            echo "::set-output name=basename::$(basename ${{matrix.tests}} )"
            echo "::set-output name=videos::${PWD}/${{matrix.tests}}/videos"
            echo "::set-output name=screenshots::${PWD}/${{matrix.tests}}/screenshots"
            echo "::set-output name=reports::${PWD}/${{matrix.tests}}/reports"

      - name: Run ${{ matrix.tests }} Test
        run: |
              docker run -i --shm-size=1g -e CYPRESS_SPEC -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME \
                                          -e CYPRESS_EVENT_USER_EMAIL_API_KEY -e CYPRESS_MAILING_LIST_USER_EMAIL_API_KEY -e CYPRESS_TTA_USER_EMAIL_API_KEY \
                                   -v $PWD:/test -w /test  \
                                   -v ${{steps.config.outputs.screenshots}}:/test/cypress/screenshots   \
                                   -v ${{steps.config.outputs.videos}}:/test/cypress/videos   \
                                   -v ${{steps.config.outputs.reports}}:/test/cypress/reports   \
                                   ${{ env.DOCKERHUB_REPOSITORY}}:latest
        env:
              CYPRESS_SPEC:                             "cypress/integration/${{ matrix.tests }}.spec.js"
              CYPRESS_HTTPAUTH_PASSWORD:                "${{ steps.keyvault-yaml-secret.outputs.HTTP-PASSWORD }}"
              CYPRESS_HTTPAUTH_USERNAME:                "${{ steps.keyvault-yaml-secret.outputs.HTTP-USERNAME }}"
              CYPRESS_EVENT_USER_EMAIL_API_KEY:         "${{ steps.keyvault-yaml-secret.outputs.EVENT-USER-EMAIL-API-KEY }}"
              CYPRESS_MAILING_LIST_USER_EMAIL_API_KEY:  "${{ steps.keyvault-yaml-secret.outputs.MAILING-LIST-USER-EMAIL-API-KEY }}"
              CYPRESS_TTA_USER_EMAIL_API_KEY:           "${{ steps.keyvault-yaml-secret.outputs.TTA-USER-EMAIL-API-KEY }}"
              PERCY_TOKEN:                              "${{ steps.keyvault-yaml-secret.outputs.PERCY-TOKEN }}"      
                
      - name: Upload reports artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{steps.config.outputs.basename }}
          path: |
               ${{steps.config.outputs.videos}}
               ${{steps.config.outputs.screenshots}}
               ${{steps.config.outputs.reports}}
          if-no-files-found: ignore

      - name: Count Failures
        id:  failures
        if: always()
        run: |
            cat ${{steps.config.outputs.reports}}/*.json | jq  -r ".results[].suites[].suites[].tests[] | {fullTitle , pass} | select(.pass=="false" ) | .fullTitle" > /tmp/$$.tmp
            if [[ $(cat /tmp/$$.tmp | wc -l) -gt 0  ]]
            then
                 i=0
                 echo ::set-output name=adverb::""
                 while IFS= read -r line
                 do
                   if [[ $i -gt 10 ]]
                   then
                      echo ::set-output name=adverb::first
                      break
                   fi
                   i=$((i+1))
                   echo ::set-output name=message${i}::"FAILED  - ${line}"
                 done <  /tmp/$$.tmp
                 echo ::set-output name=display::${i}
                 echo ::set-output name=number::$(cat /tmp/$$.tmp | wc -l)
                 exit 1
            fi
            exit 0

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_WEBHOOK: ${{ steps.keyvault-yaml-secret.outputs.SLACK-WEBHOOK }}
           SLACK_COLOR:   ${{env.SLACK_ERROR}}
           SLACK_TITLE: 'Failure running Cypress test ${{ matrix.tests}}'
           SLACK_MESSAGE: |
                           ${{steps.failures.outputs.number}} Cypress tests have failed,
                           here are the ${{steps.failures.outputs.adverb}} ${{steps.failures.outputs.display}} failures
                           ${{steps.failures.outputs.message1}}
                           ${{steps.failures.outputs.message2}}
                           ${{steps.failures.outputs.message3}}
                           ${{steps.failures.outputs.message4}}
                           ${{steps.failures.outputs.message5}}
                           ${{steps.failures.outputs.message6}}
                           ${{steps.failures.outputs.message7}}
                           ${{steps.failures.outputs.message8}}
                           ${{steps.failures.outputs.message9}}
                           ${{steps.failures.outputs.message10}}

  Cypress:
    name: ${{github.event.inputs.reference}}
    if: success()
    runs-on: ubuntu-latest
    needs: RunTests
    steps:
       - name: Check Task has Competed
         run: echo "Test matrix has completed"
   
  Failed:
    name: ${{github.event.inputs.reference}}
    if:    failure()
    runs-on: ubuntu-latest
    needs: RunTests
    steps:
       - name: Check Task has Failed
         run: |
               echo "Test matrix has failed"
               exit 1
