---
name: Cypress Testing (dev) (active)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
jobs:
  cypress:
    name: Run Cypress Tests (dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:   Run the Tests
        run: |
             docker build . -t cypress-image
             docker run -i --shm-size=1g   -e CYPRESS_HTTPAUTH_PASSWORD -e CYPRESS_HTTPAUTH_USERNAME  -v $PWD:/test -w /test cypress-image 
        env:
              CYPRESS_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
              CYPRESS_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
        
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: Videos
          path: ./cypress/videos/

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: Screenshots
          path: ./cypress/screenshots/

